version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: form-data
      - dependency-name: postcss
      - dependency-name: uuid
      - dependency-name: js-yaml
